### ISSUE TITLE
Missing regional aggregates

### ISSUE THREAD

**Issue by lpicci96** [owid/energy-data#19]
The raw data does not include values for South America, Oceania, Asia, North America. But the dashboard shows regional aggregates for some variables. 

![image](https://user-images.githubusercontent.com/56567716/176492199-dd3cda16-c9f4-4807-b680-aee3ac47a6ea.png)

**Comment by pabloarosado** [comment]
This issue has been solved in the latest update. Now the energy dataset contains all regions, following [the same definitions](https://ourworldindata.org/world-region-map-definitions). It is still possible that some variables do not have data for some of the regions (simply because there is no data for the member countries), but that is expected.
Thank you @lpicci96 for raising this issue!
