### ISSUE TITLE
USSR/Russia data aggregation

### ISSUE THREAD

**Issue by nuno-andre** [owid/energy-data#3]
There's a small error in the [USSR/Russia data aggregation](https://ourworldindata.org/explorers/energy?tab=chart&country=OWID_USS~RUS~UKR~KAZ~BLR&Total+or+Breakdown=Total&Energy+or+Electricity=Primary+energy&Metric=Annual+consumption).

![image](https://user-images.githubusercontent.com/6339494/114318938-797d4680-9b0f-11eb-9e83-4096ae33cc0f.png)

Thank you for your work. It's awesome!
Cheers!

**Comment by pabloarosado** [comment]
Thanks @nuno-andre for pointing this out. After updating the dataset for primary energy consumption, USSR and Russia appear [as separated time series](https://ourworldindata.org/explorers/energy?tab=chart&facet=none&country=OWID_USS~RUS~UKR~KAZ~BLR~LTU~EST~LVA&Total+or+Breakdown=Total&Energy+or+Electricity=Primary+energy&Metric=Annual+consumption). There is still some overlap in time between the two series, because different datasets (BP and EIA) have data for the USSR until different dates (1984 and 1991, respectively).
![energy](https://user-images.githubusercontent.com/12246978/161217619-e638ea73-32f0-4525-9680-1b6ece85d59f.png).
